import PyInstaller.__main__
import os

# Get the current directory
current_dir = os.path.dirname(os.path.abspath(__file__))

# Define the icon path if it exists
icon_path = os.path.join(current_dir, 'icon.ico')
icon_arg = ['--icon=' + icon_path] if os.path.exists(icon_path) else []

# Define UPX path - download UPX from https://github.com/upx/upx/releases
upx_path = os.path.join(current_dir, 'upx-4.2.2-win64', 'upx.exe')
upx_arg = ['--upx-dir=' + os.path.dirname(upx_path)] if os.path.exists(upx_path) else []

PyInstaller.__main__.run([
    'blackjack_game.py',
    '--onefile',
    '--windowed',
    '--name=Blackjack',
    '--strip',
    '--noupx',  # We'll use UPX separately
    '--clean',
    '--hidden-import=PIL._tkinter_finder',
    '--hidden-import=customtkinter',
    '--hidden-import=pytablericons',
    # Exclude unnecessary modules
    '--exclude-module=tkinter.test',
    '--exclude-module=PIL.tests',
    '--exclude-module=unittest',
    '--exclude-module=pytest',
    '--exclude-module=distutils',
    '--exclude-module=email',
    '--exclude-module=html',
    '--exclude-module=http',
    '--exclude-module=xml',
    '--exclude-module=sqlite3',
    '--exclude-module=doctest',
    '--exclude-module=pdb',
    '--exclude-module=pycparser',
    '--exclude-module=setuptools',
    '--exclude-module=pkg_resources',
    '--exclude-module=pygame.tests',
    '--exclude-module=pygame.examples',
    '--exclude-module=pygame.docs',
    '--exclude-module=pygame.threads',
    '--exclude-module=pygame.sndarray',
    '--exclude-module=pygame.mixer_music',
    '--exclude-module=pygame.mixer',
    '--exclude-module=pygame.camera',
    '--exclude-module=pygame.scrap',
    '--exclude-module=pygame.surfarray',
    '--exclude-module=pygame.midi',
    '--exclude-module=pygame.time',
    '--exclude-module=pygame.version',
    '--exclude-module=pygame.sysfont',
    '--exclude-module=pygame.font',
    '--exclude-module=pygame.display',
    '--exclude-module=pygame.event',
    '--exclude-module=pygame.key',
    '--exclude-module=pygame.mouse',
    '--exclude-module=pygame.joystick',
    '--exclude-module=pygame.cursors',
    '--exclude-module=pygame.color',
    '--exclude-module=pygame.draw',
    '--exclude-module=pygame.image',
    '--exclude-module=pygame.mask',
    '--exclude-module=pygame.math',
    '--exclude-module=pygame.pixelarray',
    '--exclude-module=pygame.pixelcopy',
    '--exclude-module=pygame.rect',
    '--exclude-module=pygame.sprite',
    '--exclude-module=pygame.surface',
    '--exclude-module=pygame.transform',
    '--exclude-module=pygame.constants',
    '--exclude-module=pygame.locals',
    '--exclude-module=pygame.error',
    '--exclude-module=pygame.init',
    '--exclude-module=pygame.quit',
    '--exclude-module=pygame.register_quit',
    '--exclude-module=pygame.get_error',
    '--exclude-module=pygame.set_error',
    '--exclude-module=pygame.get_sdl_version',
    '--exclude-module=pygame.get_sdl_byteorder',
    '--exclude-module=pygame.get_sdl_platform',
    '--exclude-module=pygame.get_sdl_runtime',
    '--exclude-module=pygame.get_sdl_revision',
    '--exclude-module=pygame.get_sdl_compiled',
    '--exclude-module=pygame.get_sdl_linked',
    '--exclude-module=pygame.get_sdl_audio',
    '--exclude-module=pygame.get_sdl_video',
    '--exclude-module=pygame.get_sdl_joystick',
    '--exclude-module=pygame.get_sdl_haptic',
    '--exclude-module=pygame.get_sdl_power',
    '--exclude-module=pygame.get_sdl_render',
    '--exclude-module=pygame.get_sdl_sensor',
    '--exclude-module=pygame.get_sdl_touch',
    '--exclude-module=pygame.get_sdl_gesture',
    '--exclude-module=pygame.get_sdl_clipboard',
    '--exclude-module=pygame.get_sdl_timer',
    '--exclude-module=pygame.get_sdl_thread',
    '--exclude-module=pygame.get_sdl_mutex',
    '--exclude-module=pygame.get_sdl_cond',
    '--exclude-module=pygame.get_sdl_sem',
    '--exclude-module=pygame.get_sdl_rwops',
] + icon_arg + upx_arg) 